services:
  postgres:
    image: postgres:13.22
    container_name: hmi_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1304
      POSTGRES_DB: hmi_web
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: